wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.18.6
    framework: huggingface
    huggingface_version: 4.46.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1731296545.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 100
      - 105
      3:
      - 4
      - 13
      - 23
      - 42
      - 55
      4: 3.10.14
      5: 0.18.6
      6: 4.46.2
      8:
      - 5
      13: linux-x86_64
